server:
  port: 8081

spring:
  output:
    ansi:
      enabled=ALWAYS:
  application:
    name: ScWaiterServiceApplication
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: config,stat,slf4j
      driver-class-name: org.h2.Driver
      initial-size: 5
      max-active: 5
      min-idle: 5
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      validationQuery: select 1
  h2:
    console:
      enabled: true
  cache:
    redis:
      cache-null-calues: false
      time-to-live: 1200000ms
      use-key-prefix: true
  redis:
    host: localhost
    port: 6379
    pass:
    database: 0
    lettuce:
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
        max-wait: -1ms
        shutdown-timeout: 200ms

mybatis:
  type-handlers-package: com.springbucks.sc.waiter.handler
  configuration:
    map-underscore-to-camel-case: true
